<?php

/**
 * Implementation of hook_permission().
 */
function numahub_custom_permission() {
  return array(
    'access numahub interface' => array(
      'title' => t('Access NumaHub Interface'),
      'description' => t('Allow access to the NumaHub Interface.'),
    ),
  );
}


/**
 * Implementation of hook_menu().
 */
function numahub_custom_menu() {
  $items = array();

  $items['interface'] = array(
    'title'            => 'Chat',
    'access arguments' => array('access numahub interface'),
    'page callback'    => 'numahub_custom_page',
    'type'             => MENU_CALLBACK,
  );

  $items['analytics/data/%'] = array(
        'type' => MENU_NORMAL_ITEM, 
        'title' => 'Analytics Data',
        'page arguments' => array(1,2,3),
        'page callback' => 'numahub_custom_data',
        'access callback' => 'user_access', 
        'access arguments' => array('access numahub interface'),
    );

  return $items;
}



function numahub_custom_data(){
  return "Nothing";
}
/**
 * Implementation of hook_theme().
 */
function numahub_custom_theme() {
  return array(
    'numahub_custom' => array(
      'template' => 'tpl/numahub_custom',
      'arguments' => array('username' => NULL),
    ),
  );
}


/**
 * Page callback for /chat menu item.
 */
function numahub_custom_page() {
  global $user;
  return theme('numahub_custom', array('username' => $user->name));
}
